import * as assert from 'assert';
import { categorizeDefinitions, assembleScript } from '../codegen/targets/arduino/python/assemble';

suite('python categorizeDefinitions', () => {
    test('splits definitions by key prefix and the variables key', () => {
        const s = categorizeDefinitions({
            'variables': 'count = None',
            'import_a': 'import time',
            'decl_a': 'THRESHOLD = 10',
            'func_blink': 'def blink():\n    pass',
            'setup_a': 'Leds.begin()',
        });
        assert.strictEqual(s.variables, 'count = None');
        // imports always include the App Lab entry point import.
        assert.deepStrictEqual(s.imports, ['import time', 'from arduino.app_utils import App']);
        assert.deepStrictEqual(s.declarations, ['THRESHOLD = 10']);
        assert.deepStrictEqual(s.helpers, ['def blink():\n    pass']);
        assert.deepStrictEqual(s.setup, ['Leds.begin()']);
    });

    test('classifies bare import/from lines and skips empty values', () => {
        const s = categorizeDefinitions({ 'x': 'from machine import Pin', 'y': '', 'z': 'value = 1' });
        assert.ok(s.imports.includes('from machine import Pin'));
        assert.deepStrictEqual(s.declarations, ['value = 1']);
    });
});

suite('assembleScript', () => {
    const INDENT = '    ';
    const PASS = 'pass';

    test('empty workspace yields a pass loop and the App.run entry point', () => {
        const out = assembleScript({}, '', INDENT, PASS, new Set());
        assert.ok(out.startsWith('# This code has been automatically generated by Maker Block Studio.'), out);
        assert.ok(out.includes('from arduino.app_utils import App'), out);
        assert.ok(out.includes('def loop():\n    pass'), out);
        assert.ok(out.trimEnd().endsWith('App.run(user_loop=loop)'), out);
    });

    test('omits the timestamp line when no generatedAt is given', () => {
        const out = assembleScript({}, '', INDENT, PASS, new Set());
        assert.ok(!out.includes('# Last generated:'), out);
    });

    test('stamps the generation timestamp in the header when provided', () => {
        const out = assembleScript({}, '', INDENT, PASS, new Set(), '2026-06-14 12:34:56 UTC');
        assert.ok(out.includes('# Last generated: 2026-06-14 12:34:56 UTC'), out);
        assert.ok(out.indexOf('# Last generated:') < out.indexOf('# --- Imports ---'), out);
    });

    test('wraps top-level statements into loop()', () => {
        const out = assembleScript({}, '    print("hi")', INDENT, PASS, new Set());
        assert.ok(out.includes('def loop():\n    print("hi")'), out);
    });

    test('injects a global declaration into loop() when module vars exist', () => {
        const out = assembleScript(
            { 'variables': 'count = None' },
            '    count = count + 1',
            INDENT, PASS, new Set(),
        );
        assert.ok(out.includes('# --- Variables ---\ncount = None'), out);
        assert.ok(out.includes('def loop():\n    global count\n    count = count + 1'), out);
    });

    test('injects `global` into a module-level function declaration that mutates a var', () => {
        // injectGlobals applies to the declarations zone (decl_*).
        const out = assembleScript(
            { 'variables': 'count = None', 'decl_inc': 'def inc():\n    count = count + 1' },
            '', INDENT, PASS, new Set(),
        );
        assert.ok(out.includes('def inc():\n    global count\n    count = count + 1'), out);
    });

    test('strips parameter names from a helper\'s existing `global` line', () => {
        // cleanGlobals applies to the helpers zone (func_*): params are locals.
        const out = assembleScript(
            { 'func_cb': 'def cb(evt):\n    global evt, count\n    count = evt' },
            '', INDENT, PASS, new Set(['evt']),
        );
        assert.ok(out.includes('global count') && !out.includes('global evt'), out);
    });

    test('orders sections: imports, variables, declarations, helpers, setup, loop', () => {
        const out = assembleScript(
            {
                'import_a': 'import time',
                'variables': 'count = None',
                'decl_a': 'THRESHOLD = 10',
                'func_h': 'def h():\n    pass',
                'setup_a': 'Leds.begin()',
            },
            '    count = count + 1',
            INDENT, PASS, new Set(),
        );
        const order = ['# --- Imports ---', '# --- Variables ---', '# --- Declarations ---', '# --- Helper functions ---', '# --- Setup ---', 'def loop():'];
        let last = -1;
        for (const marker of order) {
            const idx = out.indexOf(marker);
            assert.ok(idx > last, `${marker} out of order in:\n${out}`);
            last = idx;
        }
    });
});
