import * as assert from 'assert';
import { categorizeDefinitions, assembleSketch, SketchSections } from '../codegen/targets/arduino/cpp/assemble';

suite('categorizeDefinitions', () => {
    test('splits definitions by key prefix, preserving order', () => {
        const s = categorizeDefinitions({
            'import_a': '#include <Wire.h>',
            'import_b': '#include <Modulino.h>',
            'decl_a': 'ModulinoThermo _thermo;',
            'func_blink': 'void blink() {}',
            'setup_a': '_thermo.begin();',
        });
        assert.deepStrictEqual(s.includes, ['#include <Wire.h>', '#include <Modulino.h>']);
        assert.deepStrictEqual(s.declarations, ['ModulinoThermo _thermo;']);
        assert.deepStrictEqual(s.helpers, ['void blink() {}']);
        assert.deepStrictEqual(s.setup, ['_thermo.begin();']);
    });

    test('ignores unknown prefixes (e.g. cleanup_) and empty values', () => {
        const s = categorizeDefinitions({ 'cleanup_x': 'foo();', 'setup_e': '', 'decl_x': 'int n;' });
        assert.deepStrictEqual(s.setup, []);
        assert.deepStrictEqual(s.declarations, ['int n;']);
    });
});

suite('assembleSketch', () => {
    const empty: SketchSections = { includes: [], declarations: [], helpers: [], setup: [] };

    test('empty workspace yields empty setup() and loop() stubs', () => {
        const out = assembleSketch(empty, '');
        assert.ok(out.includes('void setup() {\n}'), out);
        assert.ok(out.includes('void loop() {\n}'), out);
        assert.ok(out.startsWith('// Generated by PlatformIO Blocks'), out);
    });

    test('places setup sections inside setup(), indented', () => {
        const out = assembleSketch({ ...empty, setup: ['Wire1.begin();', '_thermo.begin();'] }, '');
        assert.ok(out.includes('void setup() {\n  Wire1.begin();\n\n  _thermo.begin();\n}') === false);
        // setup lines are joined with '\n' and indented:
        assert.ok(out.includes('void setup() {\n  Wire1.begin();\n  _thermo.begin();\n}'), out);
    });

    test('wraps top-level statements into loop(), indented', () => {
        const out = assembleSketch(empty, 'digitalWrite(13, HIGH);\ndelay(100);');
        assert.ok(out.includes('void loop() {\n  digitalWrite(13, HIGH);\n  delay(100);\n}'), out);
    });

    test('orders sections: includes, declarations, helpers, setup, loop', () => {
        const out = assembleSketch(
            {
                includes: ['#include <Arduino.h>'],
                declarations: ['int counter;'],
                helpers: ['void helper() {}'],
                setup: ['Serial.begin(9600);'],
            },
            'counter++;'
        );
        const iInc = out.indexOf('#include <Arduino.h>');
        const iDecl = out.indexOf('int counter;');
        const iHelp = out.indexOf('void helper()');
        const iSetup = out.indexOf('void setup()');
        const iLoop = out.indexOf('void loop()');
        assert.ok(iInc < iDecl && iDecl < iHelp && iHelp < iSetup && iSetup < iLoop, out);
    });
});
