/**
 * Assembles a complete Arduino App Lab Python script from the generator's
 * `definitions_` map plus the loop body (the concatenation of top-level
 * workspace statements).
 *
 * The Python analogue of `src/codegen/targets/arduino/cpp/assemble.ts`: routes
 * the generator's `definitions_` map (keyed by the conventional prefixes
 * import_/decl_/func_/setup_, plus the PythonGenerator's own `variables` key)
 * into a script — header → imports (auto-adds `from arduino.app_utils import
 * App`) → variables → declarations → helpers → setup → `def loop():` (top-level
 * statements) → `App.run(user_loop=loop)`.
 *
 * Mirrors the Arduino App Lab model: there are no explicit setup/loop scaffold
 * blocks — every top-level statement becomes the `loop()` body, while the
 * `codegen.setup` sections collected from blocks run once before it.
 *
 * Intentionally pure (no Blockly/VS Code deps) so it is unit testable and shared
 * between the webview generator and tests.
 */

function buildHeader(generatedAt?: string): string {
    const lines = [
        '# This code has been automatically generated by Blocks Editor.',
        '# Changes are overwritten whenever the blocks are edited.',
    ];
    if (generatedAt) {lines.push(`# Last generated: ${generatedAt}`);}
    return lines.join('\n');
}

export interface ScriptSections {
    imports: string[];
    variables: string | undefined;
    declarations: string[];
    helpers: string[];
    setup: string[];
}

/**
 * Split a generator `definitions_` map into ordered script sections by key.
 * Prefixes are written by the template engine: import_/decl_/func_/setup_.
 * PythonGenerator additionally writes a single `variables` entry (module-level
 * `x = None` declarations). The `from arduino.app_utils import App` import is
 * always appended so the App Lab runtime entry point resolves.
 */
export function categorizeDefinitions(definitions: Record<string, string>): ScriptSections {
    const sections: ScriptSections = {
        imports: [],
        variables: undefined,
        declarations: [],
        helpers: [],
        setup: [],
    };
    for (const [key, value] of Object.entries(definitions)) {
        if (!value) {continue;}
        if (key === 'variables') {
            sections.variables = value;
        } else if (key.startsWith('import_')) {
            sections.imports.push(value);
        } else if (key.startsWith('decl_')) {
            sections.declarations.push(value);
        } else if (key.startsWith('func_') || key.startsWith('%')) {
            sections.helpers.push(value);
        } else if (key.startsWith('setup_')) {
            sections.setup.push(value);
        } else if (/^(?:import |from )/.test(value)) {
            sections.imports.push(value);
        } else {
            sections.declarations.push(value);
        }
    }
    sections.imports.push('from arduino.app_utils import App');
    return sections;
}

function extractVarNames(varsDef: string | undefined): string[] {
    if (!varsDef) {return [];}
    return varsDef.split('\n').map((l) => l.split(' = ')[0].trim()).filter(Boolean);
}

export function assembleScript(
    definitions: Record<string, string>,
    loopBody: string,
    indentStr: string,
    passStr: string,
    paramVarNames: Set<string>,
    generatedAt?: string,
): string {
    const s = categorizeDefinitions(definitions);
    const varNames = extractVarNames(s.variables);
    const globalLine = varNames.length
        ? `${indentStr}global ${varNames.join(', ')}\n`
        : '';

    // Module-level variables assigned inside a helper need a `global` line.
    const injectGlobals = (decl: string): string => {
        if (!varNames.length) {return decl;}
        const match = decl.match(/^(def\s+\w+\([^)]*\):\s*\n)/);
        if (!match) {return decl;}
        const fnBody = decl.slice(match[1].length);
        const used = varNames.filter((v) => fnBody.includes(v));
        if (!used.length) {return decl;}
        return match[1] + `${indentStr}global ${used.join(', ')}\n` + fnBody;
    };

    // Parameter names are locals, never module globals — strip them from any
    // `global` line a helper carried over from generation.
    const cleanGlobals = (helper: string): string => {
        if (!paramVarNames.size) {return helper;}
        return helper.replace(
            /^( +global )(.+)$/m,
            (line, prefix: string, vars: string) => {
                const cleaned = vars.split(', ').filter((v) => !paramVarNames.has(v));
                return cleaned.length ? prefix + cleaned.join(', ') : '';
            },
        );
    };

    const body = loopBody
        ? globalLine + loopBody
        : indentStr + passStr;

    const sections: string[] = [];
    sections.push(buildHeader(generatedAt));
    sections.push('# --- Imports ---\n' + s.imports.join('\n'));
    if (s.variables) {sections.push('# --- Variables ---\n' + s.variables);}
    if (s.declarations.length) {sections.push('# --- Declarations ---\n' + s.declarations.map(injectGlobals).join('\n\n'));}
    if (s.helpers.length) {sections.push('# --- Helper functions ---\n' + s.helpers.map(cleanGlobals).join('\n\n'));}
    if (s.setup.length) {sections.push('# --- Setup ---\n' + s.setup.join('\n\n'));}
    sections.push(`def loop():\n${body}`);
    sections.push('App.run(user_loop=loop)');

    return sections.join('\n\n') + '\n';
}
