/**
 * Assembles a complete Arduino C++ sketch from the generator's `definitions_`
 * map plus the loop body (the concatenation of top-level workspace statements).
 *
 * Mirrors the Arduino App Lab model: there are no explicit setup/loop scaffold
 * blocks — every top-level statement becomes the `loop()` body, while the
 * `codegen.setup` sections collected from blocks become the `setup()` body.
 *
 * This module is intentionally pure (no Blockly/VS Code deps) so it is unit
 * testable and shared between the webview generator and tests.
 */

export interface SketchSections {
    includes: string[];
    declarations: string[];
    helpers: string[];
    setup: string[];
}

const HEADER = [
    '// Generated by PlatformIO Blocks — do not edit.',
    '// Changes are overwritten whenever the blocks are edited.',
].join('\n');

const INDENT = '  ';

/**
 * Split a generator `definitions_` map into ordered sketch sections by key prefix.
 * Prefixes are written by the template engine: import_/include_, decl_, func_, setup_.
 * Insertion order is preserved (keys are non-numeric). Unknown prefixes (e.g.
 * cleanup_) are ignored for C++.
 */
export function categorizeDefinitions(definitions: Record<string, string>): SketchSections {
    const sections: SketchSections = { includes: [], declarations: [], helpers: [], setup: [] };
    for (const [key, value] of Object.entries(definitions)) {
        if (!value) continue;
        if (key.startsWith('import_') || key.startsWith('include_')) sections.includes.push(value);
        else if (key.startsWith('decl_')) sections.declarations.push(value);
        else if (key.startsWith('func_')) sections.helpers.push(value);
        else if (key.startsWith('setup_')) sections.setup.push(value);
    }
    return sections;
}

function indentBlock(code: string): string {
    return code
        .split('\n')
        .map(line => (line.length ? INDENT + line : line))
        .join('\n');
}

function wrapFunction(name: string, body: string): string {
    const trimmed = body.replace(/\n+$/, '');
    return trimmed ? `${name} {\n${indentBlock(trimmed)}\n}` : `${name} {\n}`;
}

export function assembleSketch(sections: SketchSections, loopBody: string): string {
    const parts: string[] = [HEADER];

    if (sections.includes.length) parts.push(sections.includes.join('\n'));
    if (sections.declarations.length) parts.push(sections.declarations.join('\n'));
    if (sections.helpers.length) parts.push(sections.helpers.join('\n\n'));

    parts.push(wrapFunction('void setup()', sections.setup.join('\n')));
    parts.push(wrapFunction('void loop()', loopBody ?? ''));

    return parts.join('\n\n') + '\n';
}
